### ISSUE TITLE
DSE sweep parameters with single values break the script 

### ISSUE THREAD

**Issue by kgpierce** [INTO-CPS-Association/into-cps-application#111]
If you are editing a DSE configuration in the App and provide a single value, this is saved as a singleton rather than a list with one element. The DSE script then attempts to do "for x in" and returns that int/real is not iterable. If you manually add square bracket sin the JSON it works fine, but the App will strip them out the next time you save.

For example, the following works fine...
```
"parameters": {  
        "{Robotti}.RobottiInstance.cAlphaF": [20000, 24500, 29000, 33500, 38000]
    },
```
If we change to a single value the app will save like this:
```
"parameters": {  
        "{Robotti}.RobottiInstance.cAlphaF": 20000
    },
```
Which causes an error, whereas the App could save like this:
```
"parameters": {  
        "{Robotti}.RobottiInstance.cAlphaF": [20000]
    },
```
We might argue that sweeping one value doesn't make sense, but it's easy to get to this situation if you want to reduce the running time during testing, or override a parameter.

**Comment by Unsongheroes** [comment]
Thank you for letting us know. This issue has been fixed in commit#75454346e53c08caeacac8a43a1d50fa9466b3b9, and will be part of the 4.0.1 release.
