### ISSUE TITLE
COE tries to load win64 library on a win32 fmu

### ISSUE THREAD

**Issue by clagms** [INTO-CPS-Association/into-cps-application#12]
Scenario to reproduce:
1. Download into-cps-app-3.4.6-win32-ia32;
1. Open the project given in  [MSD_Project.zip](https://github.com/INTO-CPS-Association/into-cps-application/files/2173983/MSD_Project.zip)
 (fmus were exported from openmodelica and omedit v1.12);
1. Run the co-simulation.
1. The FMU log should be similar to (see [bug_log.txt](https://github.com/INTO-CPS-Association/into-cps-application/files/2173982/bug_log.txt)):
```
...
ERROR [NanoHttpd Request Processor (#1)] (DirectoryFmu.java:120) - Fmu do not conform to the standard. Unable to obtain modelIndentifier 'MassSpringDamper1' for co-simulation, defaulting to archieve name 'MassSpringDamper1' 
WARN [NanoHttpd Request Processor (#1)] (DirectoryFmu.java:121) - Attempting to recover loading of the library by setting modelIndentifier='MassSpringDamper1' 
ERROR [NanoHttpd Request Processor (#1)] (RequestProcessors.java:330) - Internal error in initialization 
org.intocps.orchestration.coe.AbortSimulationException: An FMU library didn't load 
{MassSpringDamper1} library does not exist: 
C:\Users\clagm\AppData\Local\Temp\MassSpringDamper14497606786479894800\binaries\win64\MassSpringDamper1.dll 
```

There might be something wrong with the model identifier of the FMU, but there is an attempt at loading the right file name, in the wrong directory.

**Comment by CThuleHansen** [comment]
Which version of the into-cps-application are you using? 64 or 32 bit?

**Comment by CThuleHansen** [comment]
I think it is because you are using JVM 64-bit to run the COE

**Comment by CThuleHansen** [comment]
The solution to this, from an UI perspective, is to disable the simulate button if the platform and architecture does not match the binaries provided.
