### ISSUE TITLE
Add a drop down menu for number of threads in the DSE Configure Harmonica/Panel

### ISSUE THREAD

**Issue by idhugoid** [INTO-CPS-Association/into-cps-application#131]
Either a range of numbers 2 - 10 or allow number input and filter: Positive integer...

It should be independent of the Search Algorithm "choice" because it affects the different option Exhaustive and Genetic. Maybe a container for DSE COE/Runtime Configuration.

**Comment by idhugoid** [comment]
This is good to go now, it was fixed Maestro 2

**Comment by maxs-rose** [comment]
See pr #143
