### ISSUE TITLE
Make the csv and html generation optional

### ISSUE THREAD

**Issue by idhugoid** [INTO-CPS-Association/into-cps-application#132]
Add two check boxes that are passed in the command line args of the Python scripts... Add this to the threads container group described in #128

**Comment by idhugoid** [comment]
-t: Number of threads to use, default 1 Please note this is currently an experimental feature and may cause simulations to fail

-noCSV: do not generate CSV result file, default false
-noHTML: do not generate HTML result file, default false

**Comment by maxs-rose** [comment]
see #144
