### ISSUE TITLE
Unchecking the development version option in the Settings is not working

### ISSUE THREAD

**Issue by idhugoid** [INTO-CPS-Association/into-cps-application#138]
When we check that option in the Settings menu the settings file overwrites 
AppData\Roaming\INTO-CPS APP\intoCpsApp\settings.json.

the update_site to point to development:   

update_site: 'https://raw.githubusercontent.com/INTO-CPS-Association/INTO-CPS-Association.github.io/development/download/',
  dev_update_site: 'https://raw.githubusercontent.com/INTO-CPS-Association/INTO-CPS-Association.github.io/development/download/',

The unchecking should overwrite the update_site again.

Or the download manager should just use the checkbox to choose the right link, without overwriting it...

**Comment by gi11** [comment]
Fixed in commit dd6cd41
