### ISSUE TITLE
version 4.0.2 does not update the crc of the multimodel

### ISSUE THREAD

**Issue by mapalmieri** [INTO-CPS-Association/into-cps-application#148]
when changing the multimodel of a project, the co-simulation cannot be simulated because of a warning saying: "Multimodel crc check failed. Multimodel has changed." The previous version allows users to Edit and Save the configuration to solve the warning. This version does not.

Tried on Ubuntu 16 with the AppImage file.

So far a workaround is to also open the previous version, Edit and Save the co-simulation configuration on the previous version, then the warning disappears also on version 4.0.2 of the app.

**Comment by Unsongheroes** [comment]
This should be solved in 4.0.3, you should be able to verify this in the release candidate: https://github.com/INTO-CPS-Association/into-cps-application/releases/tag/v4.0.3-rc. I will close this issue for now, if this issue persists please let us know.
