### ISSUE TITLE
On interpretation crash, it shall still be possible to retrieve the specification

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/into-cps-application#165]
Maestro2 is split into two phases:
Specification Generation and 
Specificaiton Execution.

The mabl specification shall be retrieved, if one exists.

If the specification execution fails, then it can still be very used to retrieve the generation specification for debugging purposes.

So this is to retrieve the generated specification, even if the execution failed, if such a specification exists.

Companion issue in Maestro https://github.com/INTO-CPS-Association/maestro/issues/344

**Comment by FrederikPM** [comment]
A possible fix is available at [](https://github.com/INTO-CPS-Association/into-cps-application/commit/06998215eff7b29a3adf7ccd58c8af4e3ff28a8d).
However, the issue is blocked until the fix can be tested with a FMU that fails at execution.
