### ISSUE TITLE
Error in loading FMUs with Enumeration type

### ISSUE THREAD

**Issue by mapalmieri** [INTO-CPS-Association/into-cps-application#182]
It appears that the Enumeration type is not considered in the FMU.js file, and as such the application does not work when using FMUs with this type (**OpenModelica** automatically uses this type for integrator).

The problem happens as soon as an FMU (with at least one variable of type Enumeration) is added in the configuration of a Multi-Model.
The problem is raised at the line 164 of Fmu.js(formatted with the chrome dev tools), when iterating on a variable of type Enumeration

Attached, a picture of the error shown on the console.
![EnumerationType_Error](https://user-images.githubusercontent.com/26796479/153402241-1fed9c68-0774-450a-b503-c1069015800b.png)

**Comment by mapalmieri** [comment]
tested on the latest application, 4.0.5 but also in 4.0.4 and 4.0.0 on Ubuntu 16.
Contact me if you need an FMU to replicate the bug, I cannot attach it on github

**Comment by levisen** [comment]
[LSR.fmu.zip](https://github.com/INTO-CPS-Association/into-cps-application/files/8948786/LSR.fmu.zip)

**Comment by clagms** [comment]
this issue is also causing https://github.com/INTO-CPS-Association/into-cps-application/issues/214

A workaround is explained in https://github.com/INTO-CPS-Association/into-cps-application/issues/214#issuecomment-1602223618
