### ISSUE TITLE
Reword 'Internal server error' message upon co-simulation failure

### ISSUE THREAD

**Issue by kgpierce** [INTO-CPS-Association/into-cps-application#221]
When a co-simulation fails, the main interface above the graphs provides a red error message with 'Internal server error' which causes confusion, particularly new users. What users then need to do is to go to the log and actually see what the error might be.

If the message could say 'Co-simulation error (see COE Log for details)' or something similar, this would be much more helpful.

I don't know if there's more than one error which can yield 'internal server error' but if useful wording can be produced in each case, that would be great.

Happy to help on any wording.

**Comment by prasadtalasila** [comment]
Completed in PR #225
