### ISSUE TITLE
Merge COE Log into COE Console

### ISSUE THREAD

**Issue by kgpierce** [INTO-CPS-Association/into-cps-application#222]
I cannot remember why we ended up with both the COE Console and COE Log, but it's confusing (even to me) that we have both. I propose we simply keep the COE Console (since it has the extra buttons to stop the COE etc.) and have the contents of COE Log piped there. We could simply rename it to 'Console' as well as this is the more familiar term.

**Comment by prasadtalasila** [comment]
Completed in PR #225
