### ISSUE TITLE
COE console can become out-of-sync

### ISSUE THREAD

**Issue by kgpierce** [INTO-CPS-Association/into-cps-application#4]
I got into a situation where the lower console thought the COE was running with a given PID, but the COE had terminated. I was then unable to launch the COE or convince the lower console that the COE wasn't running. The co-simulation config (via HTTP) is aware of the actual status.

Suggested steps to reproduce:

* Launch the COE via the lower console
* Kill it via command line or co-sim configuration view

**Comment by CThuleHansen** [comment]
Hi Ken,

I have tried to replicate this without luck.
Can you try to write a bug report again next time it happens?

**Comment by CThuleHansen** [comment]
Closed. Reopen if issue occurs again.
