### ISSUE TITLE
Simulation is not working

### ISSUE THREAD

**Issue by olafur-skulason** [INTO-CPS-Association/into-cps-application#7]
When running the lfr-non3d model in linux it is not working.

The sensor blocks do not seem get any input.
The robot is moving in a straight line.

**Comment by olafur-skulason** [comment]
Java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
Ubuntu 16.04 LTS 64 bit virtual machine

**Comment by idhugo** [comment]
Hi @olafur-skulason

I was able to solve the issue using 2 different FMUs...

You just need to unzip the file attached and paste the fmus inside into the FMUs folder in your project...

[New Sensors.zip](https://github.com/INTO-CPS-Association/into-cps-application/files/1927482/New.Sensors.zip)
