### ISSUE TITLE
Failed to parse model description due to missing fmuapi lib.

### ISSUE THREAD

**Issue by clegaard** [INTO-CPS-Association/into-cps-application#76]
![image](https://user-images.githubusercontent.com/18687499/75356720-9c6b7d80-58b0-11ea-9607-efc8d6f7eea8.png)

COE log:

![image](https://user-images.githubusercontent.com/18687499/75357818-4697d500-58b2-11ea-93f2-3639d8c3f253.png)

**Comment by CThuleHansen** [comment]
This is most likely due to your java version. We support java 8 and is prototyping java13. What version of java are you using? Can you try java 8?

**Comment by clegaard** [comment]
This was on a students computer, so i am afraid it is not possible for me to test this.
Does the parsing happen in the COE? If so, would it be possible to set up some automated testing of this with different java versions?

**Comment by clagms** [comment]
Maybe we need a small check that checks the java version installed and blows up if it is not java 8?
I had the exact same issue, and it was because of the java version being 13.
I agree that the error is obscure and difficult to relate to the wrong java version.

**Comment by clegaard** [comment]
A student worker has already implemented a check to ensure that JRE is available as far as i know.
It should be straight forward to extend this to also check for comparability as well.

**Comment by CThuleHansen** [comment]
Closing... Reopen if needed
