### ISSUE TITLE
Live Plotting not working

### ISSUE THREAD

**Issue by hbartle** [INTO-CPS-Association/into-cps-application#8]
When running the Tutorial 1 (Three Water Tank Simulation),  I get proper results but somehow the Live Plotting is not working. It works on another machine with the same following configurations:

OpenJDK 8
Arch Linux with vanilla 4.15.15-1-ARCH Kernel
Electron v1.8.4
INTO-CPS  3.4.6

Accessing the COE API through curl and browser works.

**Comment by CThuleHansen** [comment]
Currently Arch Linux is not supported.
