### ISSUE TITLE
TypeError: Cannot read property 'extScrObjectives' of undefined, while selecting the experiment multi-model of a DSE

### ISSUE THREAD

**Issue by clagms** [INTO-CPS-Association/into-cps-application#87]
Scenario to reproduce:
1. Open into-cps app.
1. Open the developer console.
1. Open the line follower example project.
1. Open a DSE configuration (for example, `lfr-16sensorPositionsConstrained`).
1. Launch the COE.
1. Select the `co-sim-14 | lfr-non-3d` multimodel.
1. Note the error on the console.

The error looks like this:
![image](https://user-images.githubusercontent.com/871103/79306515-a5162280-7ef5-11ea-9d27-de2b4d371d59.png)

And says something like:
```
TypeError: Cannot read property 'extScrObjectives' of undefined
```

Workaround (mentioned to me by @idhugo):
- Don't start the COE before selecting the multi-model (i.e., switch step 5 and step 6 above).

The nastiness of this error is over the top, because:
1. There seems to be no dependency between the COE and a DSE configuration
1. A user who manages to make this work, may discover that, on a second try, it no longer works. Because of 1., the user will think that the problem lies in the DSE json configuration, and will be looking for a solution in the wrong direction.

**Comment by Unsongheroes** [comment]
this should be fixed with the latest version on the development branch.
