### ISSUE TITLE
Javascript error when launching maestro - Ubuntu 18.04

### ISSUE THREAD

**Issue by gitting-around** [INTO-CPS-Association/into-cps-application#92]
When I try to launch maestro from the intocps app ob Ubuntu 18.04 I get the javascript error attached.
![error](https://user-images.githubusercontent.com/11443476/94165390-729c2880-fe8a-11ea-9f53-4ddd373052fb.png)

**Comment by clagms** [comment]
Dear @gitting-around the error seems to be some indirect effect of something else that failed (possibly the start of the coe server).

Please add a bit more details to help reproduce the problem:
- What example are you using? 
- What steps did you follow?
- What tool version is being used?

Some things to try:
- Open the electron console (inside the Help menu I think), reproduce the problem, and copy all the messages there.
- Check if you have the correct java version installed for the COE (please check the installation instructions for these details as my memory is fuzzy).

Thank you for spotting this!

**Comment by gitting-around** [comment]
"Check if you have the correct java version" --> this turned out to be the key. Java was not installed. I was following the steps in the readme in 'resources/app/' for intocps, and didn't look into the instructions for maestro itself, so it didn't occur to me to check for java. Sorry!

**Comment by clagms** [comment]
No need to apologise. This error message should never have occurred in the first place. The into-cps app should replay any error message it encounters when trying to start maestro in the background.

**Comment by gitting-around** [comment]
Okej. As Hugo suggested we tried the same experiment with development branch (initially I tried with the release version for linux). The issue was the same. It doesn't seem to print anything to the console related to the javascript error. See attached. 
![error on console](https://user-images.githubusercontent.com/11443476/94265099-3cb57d80-ff38-11ea-8307-540237c4b5f5.png)

**Comment by idhugoid** [comment]
Hi @gitting-around. After some more trials, I found a call to the dialog that works on my local machine. Can you pull from the repo and test if it works on your machine?

**Comment by gitting-around** [comment]
It is working on ubuntu now, it says that java is missing.
