### ISSUE TITLE
New fmu instances are not saved, if no input-outputs are connected

### ISSUE THREAD

**Issue by gitting-around** [INTO-CPS-Association/into-cps-application#93]
When adding a new instance of an fmu, and saving without establishing any input-output connections with the rest of the fmus, this new instance is not saved.
The following error can be seen:

![Screenshot 2020-10-09 at 15 12 59 (2)](https://user-images.githubusercontent.com/11443476/95587193-0866b480-0a42-11eb-983a-e4b3a4aba5c2.png)

I am running the 4.0.0 release version of the intocps app, on Mac Catalina.

I tried this with the [example-single_watertank_rabbitmq](https://github.com/INTO-CPS-Association/example-single_watertank_rabbitmq.git) project. In the multi-model configuration, I add a new fmu, and use one of the existing ones in the FMUS folder. I then create a new instance of it, and click save. The new instance is not saved.

**Comment by clagms** [comment]
This is a know problem @gitting-around ...
I'm not sure there's an easy solution for it.
Perhaps the best is to give some kind of warning that instances that are not connected (or, I think, that have a parameter defined) will be deleted.
It's a strange design choice but if you look at the JSON file, you'll see that there's no place to declare instances. Instead, instances are inferred from their connections and parameters. 
This makes JSON files less redundant, and also easier to avoid inconsistencies, but brings problems like this one...

**Comment by Unsongheroes** [comment]
@gitting-around can you check if with change fixes the issue that you were having.

**Comment by gitting-around** [comment]
@Unsongheroes, yes it works. It's possible to create and save a new instance, without making any connections.
