### ISSUE TITLE
Port parameter in preferences

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/into-cps-application#99]
It is possibly to pass -p as a command line argument to the COE when launching it.
It would be nice with a possibility of setting the port in the preferences panel.

**Comment by idhugoid** [comment]
Hi Casper! I see you also are testing the new Maestro with the app. I had the same problem today. It looks like we already are able to set that in the Settings. Meanwhile I have just pushed a the default port to the Maestro repo, so from next release on, we can just keep it in 8082...
